### ISSUE TITLE
Make the clear the fact that you need to have basic OO programming knowledge

### ISSUE THREAD

**Issue by Luki120** [NightwindDev/Tweak-Tutorial#11]
Many people that want to start making tweaks don’t realize they need to learn a fairly *decent* amount of Objective-C or at least Swift for them to be able to make somewhat complex tweaks and not having to ask syntax questions for 6 months or even more. Should probably be at the top of the first file, below the disclaimer of hooking methods.

**Comment by NightwindDev** [comment]
Added.
